### PR TITLE
Fix sum of roll

### LINKED ISSUE #23: The total amount of dice rolls is not calculated.
A message reply takes it literal. Instead of calculating a result, it combines arguments when passing numerals.
```
Du würfelst: 5 (Gesamt: 5++5=+55)
```

### PR DESCRIPTION
**Pull request by TobenderZephyr**
fixes #23

### CODE REVIEW

File: commands/Roll.js [hunk 1]
```diff
@@ -12,11 +12,13 @@ module.exports = {
 	async exec(message, args) {
 		let params = args.join('').split(globals.DiceRegex);
 		if ( params.length >= 2 ) {
-			const Bonus = params[2] || 0;
+			const Bonus = parseInt(params[2]) || 0;
```
Comment (TobenderZephyr) [inline commands/Roll.js:15]: was the initial problem since this string is not parsed as an integer.

File: commands/Roll.js [hunk 2]
```diff
@@ -12,11 +12,13 @@ module.exports = {
...
 			const numberOfDice = parseInt( params[0] );
 			const diceValues = parseInt( params[1] );
 			const result = roll( numberOfDice, diceValues, message.author.tag );
-			message.reply(`${findMessage('ROLL')} ${result.dice.join(', ')} (Gesamt: ${result.sum} + ${Bonus} = ${result.sum + Bonus})` );
+			let total = (Bonus ? Bonus + result.sum : result.sum)
+			message.reply(`${findMessage('ROLL')} ${result.dice.join(', ')} `+
+					`(Gesamt: ${result.sum}${Bonus ? `+${Bonus}=${total}` : ``})` );
```
Comment (TobenderZephyr) [inline commands/Roll.js:21]: calculation is shown, if there was a bonus.
